image: python:3.7-alpine

test:
  stage: test
  script:
  - pip install -U sphinx
  - sphinx-build -b html ./docs public
  only:
  - branches
  except:
  - main

black:
  stage: test
  before_script:
  - apt install gcc
  - pip install -U black
  script:
  - black --check ./atlas

pages:
  stage: deploy
  script:
  - pip install -U sphinx
  - sphinx-build -b html ./docs public
  artifacts:
    paths:
    - public
  only:
  - main
