image: ubuntu:20.04

before_script:
- apt-get update
- apt-get -y upgrade
- apt-get -y install gcc python3 python3-pip

test:
  stage: test
  script:
  - pip install -U sphinx furo
  - sphinx-build -b html ./docs public
  only:
  - branches
  except:
  - main

black:
  stage: test
  script:
  - pip install -U black
  - black --check ./collagen

pages:
  stage: deploy
  script:
  - pip install -U sphinx furo
  - sphinx-build -b html ./docs public
  artifacts:
    paths:
    - public
  only:
  - main
