name: DeepFrag2CPU

channels:
  - conda-forge
  - nodefaults

dependencies:
  - python=3.9
  - pip=24.0
  - setuptools>=71.0.2,<80.9
  - ProDy=2.4.1
  - rdkit=2024.3.1
  - pip:
      - flake8==4.0.1
      - mypy==1.10.0   # no typed-ast on py3.9+
      - pytest==7.1.2
      - numpy==1.23.5
      - numba==0.56.4
      - --extra-index-url https://download.pytorch.org/whl/cpu
      - torch==1.11.0
      - torchvision==0.12.0  
      - torchaudio==0.11.0
      # Note that environment.yaml uses pytorch-lightning==1.7.1. Using 1.4.9
      # here to match pip installation (which wouldn't otherwise work unless I
      # required uses to use pip<24.1)
      - pytorch-lightning==1.4.9
      - scipy==1.11.4
      - pandas==1.4.4
      - k3d==2.15.2
      - py3Dmol==2.4.0
      - h5py==3.7.0
      - scikit-learn==1.5.1
      - torchinfo==1.8.0
      - wandb==0.15.8
      - torch_geometric
      - filelock==3.13.1
      - regex
      - sacremoses==0.0.53
      - sentencepiece==0.2.0
      - tokenizers==0.20.0
      # Note that torchmetrics is 0.11.0 in the environment.yml file. Changed to
      # 0.7.3 here to be identical to pyproject.toml file (pip). When 0.11.0 is
      # used via pip: `ImportError: cannot import name 'get_num_classes' from
      # 'torchmetrics.utilities.data'`
      - torchmetrics==0.7.3
      - matplotlib==3.8.3
      - protobuf==3.20.3
      - Fancy-aggregations
      - wget
      - fair-esm
