{% set name = "deepfrag2cpu" %}
{% set version = "1.0.0" %}
package:
  name: {{ name|lower }}
  version: {{ version }}
source:
  path: ../
build:
  number: 0
  entry_points:
    - deepfrag2cpu = MainDF2:main
  noarch: python
requirements:
  host:
    - python=3.9
    - pip
    - setuptools=79.0.1
    - wheel
  run:
    - python=3.9
    - prody=2.4.1
    - rdkit=2024.3.1
    - pip
test:
  imports:
    - apps
    - collagen
    - molbert
    - transformers
  commands:
    - deepfrag2cpu --help
  requires:
    - flake8=4.0.1
    - mypy=1.10.0
    - pytest=7.1.2
about:
  home: https://github.com/yourusername/deepfrag2cpu
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: DeepFrag2CPU - Your package description here
  description: |
    Detailed description of your DeepFrag2CPU package.
  dev_url: https://github.com/yourusername/deepfrag2cpu
extra:
  recipe-maintainers:
    - yourusername